package assignment3;
import assignment3.exception.*;
import assignment3.functional.BankingOperation;
import assignment3.model.*;
import assignment3.record.*;
import assignment3.service.BankingService;
import assignment3.util.BankingReport;

import java.util.*;
import java.util.function.*;
import java.util.stream.*;
public class Main {
    private static final Scanner IN=new Scanner(System.in);
    private static final BankingService BANK=new BankingService();
    public static void main(String[] args){BANK.loadSampleData(); functionalDemo(); boolean run=true; while(run){menu(); try{switch(readInt("Choice: ")){case 1->addCustomer();case 2->BANK.customers().forEach(System.out::println);case 3->searchCustomer();case 4->addAccount();case 5->BANK.accounts().forEach(System.out::println);case 6->BANK.deposit(readLong("Account: "),readMoney("Amount: "));case 7->BANK.withdraw(readLong("Account: "),readMoney("Amount: "));case 8->BANK.transfer(readLong("Source: "),readLong("Target: "),readMoney("Amount: "));case 9->System.out.printf("Balance: ₹%.2f%n",BANK.checkBalance(readLong("Account: ")));case 10->showTransactions();case 11->System.out.println(BANK.generateBankingDashboard());case 12->customerReport();case 13->accountReport();case 14->transactionReport();case 15->statement();case 16->featureDemos();case 17->run=false;default->System.out.println("Choose 1-17");}}catch(BankingException|IllegalArgumentException e){System.out.println("Operation failed: "+e.getMessage());}catch(Exception e){System.out.println("Unexpected error: "+e.getMessage());}} System.out.println("Banking application closed.");}
    private static void menu(){System.out.println("""

========== BANKING ACCOUNT MANAGEMENT ==========
 1 Add Customer       2 Display Customers
 3 Search Customer    4 Add Account
 5 Display Accounts   6 Deposit
 7 Withdraw           8 Transfer
 9 Check Balance     10 Transaction History
 11 Analytics        12 Customer Report
 13 Account Report   14 Transaction Report
 15 Account Statement 16 Java 8/17 Demos
 17 Exit
 """);}
    private static void functionalDemo(){BankingOperation d=(x,b)->b+x,w=(x,b)->b-x,i=(x,b)->b+b*x/100;System.out.printf("Lambda demo: %.2f %.2f %.2f%n",d.execute(100,500),w.execute(100,500),i.execute(5,500));}
    private static void addCustomer(){int id=readInt("ID: ");String n=read("Name: "),e=read("Email: "),c=read("City: "),p=read("Phone: "),t=read("Type: ");BANK.addCustomer(new Customer(id,n,e,c,p,t));System.out.println("Customer added");}
    private static void searchCustomer(){int id=readInt("ID: ");BANK.findCustomer(id).ifPresentOrElse(System.out::println,()->System.out.println("Not found"));}
    private static void addAccount(){int c=readInt("Customer ID: ");long n=readLong("Account: ");String t=read("SAVINGS/CURRENT/LOAN: ").toUpperCase();double b=readMoney("Balance: ");BankAccount a=switch(t){case "SAVINGS"->new SavingsAccount(n,c,b,AccountStatus.ACTIVE);case "CURRENT"->new CurrentAccount(n,c,b,AccountStatus.ACTIVE);case "LOAN"->new LoanAccount(n,c,b,AccountStatus.ACTIVE);default->throw new IllegalArgumentException("Unknown type");};BANK.addAccount(a);}
    private static void showTransactions(){BANK.transactions().stream().sorted(Comparator.comparing(Transaction::transactionDate).reversed()).forEach(System.out::println);System.out.println("Latest five:");BANK.transactions().stream().sorted(Comparator.comparing(Transaction::transactionDate).reversed()).limit(5).forEach(System.out::println);}
    private static void customerReport(){List<Customer> c=BANK.customers();System.out.println("Names: "+c.stream().map(Customer::getName).distinct().sorted().collect(Collectors.joining(", ")));System.out.println("By city: "+c.stream().collect(Collectors.groupingBy(Customer::getCity,Collectors.counting())));System.out.println("Partition: "+c.stream().collect(Collectors.partitioningBy(x->x.getCustomerType().equals("PREMIUM"))));System.out.println("High value: "+BANK.highValueCustomers(100000));System.out.println("Top 3: "+BANK.topCustomers(3));}
    private static void accountReport(){List<BankAccount>a=BANK.accounts();System.out.println("Count/type: "+a.stream().collect(Collectors.groupingBy(BankAccount::accountType,Collectors.counting())));System.out.println("Total/type: "+a.stream().collect(Collectors.groupingBy(BankAccount::accountType,Collectors.summingDouble(BankAccount::balance))));System.out.println("Average/type: "+a.stream().collect(Collectors.groupingBy(BankAccount::accountType,Collectors.averagingDouble(BankAccount::balance))));System.out.println("Skip first: "+a.stream().sorted(Comparator.comparingDouble(BankAccount::balance).reversed()).skip(1).findFirst());}
    private static void transactionReport(){List<Transaction>t=BANK.transactions();System.out.println("Count/type: "+t.stream().collect(Collectors.groupingBy(Transaction::transactionType,Collectors.counting())));System.out.println("Total/type: "+t.stream().collect(Collectors.groupingBy(Transaction::transactionType,Collectors.summingDouble(Transaction::amount))));System.out.println("Average: "+t.stream().mapToDouble(Transaction::amount).average().orElse(0));System.out.println("Summary: "+t.stream().collect(Collectors.groupingBy(Transaction::transactionType,Collectors.summarizingDouble(Transaction::amount))));t.stream().filter(x->x.amount()>50000).forEach(System.out::println);System.out.println("Min: "+t.stream().min(Comparator.comparingDouble(Transaction::amount)));System.out.println("Max: "+t.stream().max(Comparator.comparingDouble(Transaction::amount)));}
    private static void statement(){BankAccount a=BANK.requireAccount(readLong("Account: "));System.out.println(BankingReport.statement(BANK.requireCustomer(a.customerId()),a));}
    private static void featureDemos(){Predicate<Customer> premium=c->c.getCustomerType().equals("PREMIUM"),blr=c->c.getCity().equalsIgnoreCase("Bangalore"),mlr=c->c.getCity().equalsIgnoreCase("Mangalore"),above=c->c.getCustomerId()>105;Consumer<Customer>display=System.out::println;Function<Customer,String>name=Customer::getName;Supplier<Long>number=System::currentTimeMillis;List<Customer>c=BANK.customers();System.out.println("Premium:");c.stream().filter(premium).forEach(display);System.out.println("Bangalore:");c.stream().filter(blr).forEach(display);System.out.println("Mangalore count: "+c.stream().filter(mlr).count());System.out.println("Names A: "+c.stream().map(name).filter(x->x.startsWith("A")).toList());System.out.println("ID > 105: "+c.stream().filter(above).map(name).toList());System.out.println("Ascending: "+c.stream().sorted(Comparator.comparing(Customer::getName)).toList());System.out.println("Descending: "+c.stream().sorted(Comparator.comparing(Customer::getName).reversed()).toList());System.out.println("By ID: "+c.stream().sorted(Comparator.comparingInt(Customer::getCustomerId)).toList());System.out.println("Type/name: "+c.stream().sorted(Comparator.comparing(Customer::getCustomerType).thenComparing(Customer::getName)).toList());System.out.println("Generated: "+number.get());System.out.println("Total reduce: "+BANK.accounts().stream().map(BankAccount::balance).reduce(0.0,Double::sum));System.out.println("Average: "+BANK.accounts().stream().mapToDouble(BankAccount::balance).average().orElse(0));System.out.println("flatMap: "+c.stream().flatMap(x->BANK.accounts().stream().filter(a->a.customerId()==x.getCustomerId())).map(BankAccount::accountNumber).toList());Optional<Customer>found=BANK.findCustomer(101);found.ifPresent(System.out::println);System.out.println(found.orElseGet(()->new Customer(999,"Unknown","u@x.com","Unknown","000","REGULAR")));CustomerRecord r=new CustomerRecord(101,"Rahul","Bangalore","PREMIUM");System.out.println("Record: "+r+", accessor="+r.name()+", equals="+r.equals(new CustomerRecord(101,"Rahul","Bangalore","PREMIUM")));TransactionRecord tr=new TransactionRecord(1,100001,"DEPOSIT",500);System.out.println(tr);BANK.accounts().forEach(a->System.out.println(BankingReport.accountDetails(a)));System.out.println(BankingReport.classify("DEPOSIT"));System.out.println(BankingReport.customerJson(c.get(0)));}
    private static String read(String p){System.out.print(p);return IN.nextLine().trim();} private static int readInt(String p){return Integer.parseInt(read(p));} private static long readLong(String p){return Long.parseLong(read(p));} private static double readMoney(String p){return Double.parseDouble(read(p));}
}
