package com.vikranth.ems.dao;
import com.vikranth.ems.exception.DataAccessException; import com.vikranth.ems.model.*; import com.vikranth.ems.util.ConnectionFactory;
import java.math.BigDecimal; import java.sql.*; import java.util.*;
import java.sql.Date;
public class EmployeeDaoJdbc implements EmployeeDao {
 private static Employee map(ResultSet r)throws SQLException{return new Employee(r.getInt("employee_id"),r.getString("employee_name"),r.getString("email"),r.getBigDecimal("salary"),r.getDate("hire_date").toLocalDate(),r.getInt("department_id"));}
 public int insert(Employee e){String q="INSERT INTO employee(employee_name,email,salary,hire_date,department_id) VALUES(?,?,?,?,?)";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){bind(p,e);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())return r.getInt(1);}throw new SQLException("No generated key");}catch(SQLException x){throw fail("insert employee",x);}}
 public List<Employee> findAll(){String q="SELECT * FROM employee ORDER BY employee_id";List<Employee>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));return a;}catch(SQLException x){throw fail("read employees",x);}}
 public Optional<Employee> findById(int id){String q="SELECT * FROM employee WHERE employee_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}catch(SQLException x){throw fail("find employee",x);}}
 public boolean update(Employee e){String q="UPDATE employee SET employee_name=?,email=?,salary=?,hire_date=?,department_id=? WHERE employee_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){bind(p,e);p.setInt(6,e.id());return p.executeUpdate()==1;}catch(SQLException x){throw fail("update employee",x);}}
 public boolean delete(int id){String q="DELETE FROM employee WHERE employee_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);return p.executeUpdate()==1;}catch(SQLException x){throw fail("delete employee",x);}}
 public List<Employee> findByMinimumSalary(BigDecimal min){String q="SELECT * FROM employee WHERE salary>=? ORDER BY salary DESC";List<Employee>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setBigDecimal(1,min);try(ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));}return a;}catch(SQLException x){throw fail("salary query",x);}}
 public List<EmployeeDetails> findDetailsWithDepartment(){String q="SELECT e.employee_id,e.employee_name,e.email,e.salary,d.department_name FROM employee e JOIN department d ON e.department_id=d.department_id ORDER BY e.employee_id";List<EmployeeDetails>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next())a.add(new EmployeeDetails(r.getInt(1),r.getString(2),r.getString(3),r.getBigDecimal(4),r.getString(5)));return a;}catch(SQLException x){throw fail("join query",x);}}
 public List<DepartmentCount> departmentCounts(){String q="SELECT d.department_id,d.department_name,COUNT(e.employee_id) employee_count FROM department d LEFT JOIN employee e ON d.department_id=e.department_id GROUP BY d.department_id,d.department_name ORDER BY d.department_id";List<DepartmentCount>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next())a.add(new DepartmentCount(r.getInt(1),r.getString(2),r.getLong(3)));return a;}catch(SQLException x){throw fail("aggregate query",x);}}
 public List<Employee> callEmployeesByDepartment(int deptId){List<Employee>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();CallableStatement s=c.prepareCall("{CALL sp_employees_by_department(?)}")){s.setInt(1,deptId);try(ResultSet r=s.executeQuery()){while(r.next())a.add(map(r));}return a;}catch(SQLException x){throw fail("stored procedure",x);}}
 public BigDecimal callAnnualSalary(int id){try(Connection c=ConnectionFactory.getConnection();CallableStatement s=c.prepareCall("{CALL sp_annual_salary(?,?)}")){s.setInt(1,id);s.registerOutParameter(2,Types.DECIMAL);s.execute();return s.getBigDecimal(2);}catch(SQLException x){throw fail("annual salary procedure",x);}}
 public void transfer(Connection c,int id,int dept){String q="UPDATE employee SET department_id=? WHERE employee_id=?";try(PreparedStatement p=c.prepareStatement(q)){p.setInt(1,dept);p.setInt(2,id);if(p.executeUpdate()!=1)throw new SQLException("Employee not found: "+id);}catch(SQLException x){throw fail("transfer employee",x);}}
 public int[] batchInsert(List<Employee> es){String q="INSERT INTO employee(employee_name,email,salary,hire_date,department_id) VALUES(?,?,?,?,?)";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){for(Employee e:es){bind(p,e);p.addBatch();}return p.executeBatch();}catch(SQLException x){throw fail("batch insert",x);}}
 private static void bind(PreparedStatement p,Employee e)throws SQLException{p.setString(1,e.name());p.setString(2,e.email());p.setBigDecimal(3,e.salary());p.setDate(4,Date.valueOf(e.hireDate()));p.setInt(5,e.departmentId());}
 private static DataAccessException fail(String action,SQLException x){String m=switch(x.getSQLState()==null?"":x.getSQLState()){case "23000"->"Constraint violation. Check duplicate email/key or department foreign key.";case "28000"->"Invalid database credentials.";case "42000"->"SQL syntax or database object error.";case "08S01","08001"->"Database unavailable or connection failed.";default->x.getMessage();};return new DataAccessException("Could not "+action+": "+m,x);}
}