package com.prathamesh.ems.dao;
import com.prathamesh.ems.exception.*; import com.prathamesh.ems.model.*; import com.prathamesh.ems.util.ConnectionFactory;
import java.sql.*; import java.math.BigDecimal; import java.util.*;
public class EmployeeDaoImpl implements EmployeeDao {
 private Employee map(ResultSet rs)throws SQLException{return new Employee(rs.getInt("employee_id"),rs.getString("employee_name"),rs.getString("email"),rs.getBigDecimal("salary"),rs.getInt("department_id"),rs.getDate("hire_date").toLocalDate());}
 public int add(Employee e){String q="INSERT INTO employee(employee_name,email,salary,department_id,hire_date) VALUES(?,?,?,?,?)";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){bind(p,e);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())return r.getInt(1);}throw new SQLException("No generated key");}catch(SQLException x){throw new DatabaseOperationException("Could not add employee",x);}}
 private void bind(PreparedStatement p,Employee e)throws SQLException{p.setString(1,e.name());p.setString(2,e.email());p.setBigDecimal(3,e.salary());p.setInt(4,e.departmentId());p.setDate(5,java.sql.Date.valueOf(e.hireDate()));}
 public List<Employee> findAll(){String q="SELECT employee_id,employee_name,email,salary,department_id,hire_date FROM employee ORDER BY employee_id";List<Employee> a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));return a;}catch(SQLException x){throw new DatabaseOperationException("Could not read employees",x);}}
 public Employee findById(int id){String q="SELECT employee_id,employee_name,email,salary,department_id,hire_date FROM employee WHERE employee_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){if(r.next())return map(r);throw new RecordNotFoundException("Employee "+id+" not found");}}catch(SQLException x){throw new DatabaseOperationException("Could not find employee",x);}}
 public boolean update(Employee e){String q="UPDATE employee SET employee_name=?,email=?,salary=?,department_id=?,hire_date=? WHERE employee_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){bind(p,e);p.setInt(6,e.id());return p.executeUpdate()==1;}catch(SQLException x){throw new DatabaseOperationException("Could not update employee",x);}}
 public boolean delete(int id){String q="DELETE FROM employee WHERE employee_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);return p.executeUpdate()==1;}catch(SQLException x){throw new DatabaseOperationException("Could not delete employee",x);}}
 public List<Employee> findByMinimumSalary(BigDecimal min){String q="SELECT employee_id,employee_name,email,salary,department_id,hire_date FROM employee WHERE salary>=? ORDER BY salary DESC";List<Employee>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setBigDecimal(1,min);try(ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));}return a;}catch(SQLException x){throw new DatabaseOperationException("Parameterized query failed",x);}}
 public List<EmployeeDepartmentView> findDetailsWithDepartment(){String q="SELECT e.employee_id,e.employee_name,e.email,e.salary,d.department_name,d.location FROM employee e JOIN department d ON d.department_id=e.department_id ORDER BY e.employee_id";List<EmployeeDepartmentView>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next())a.add(new EmployeeDepartmentView(r.getInt(1),r.getString(2),r.getString(3),r.getBigDecimal(4),r.getString(5),r.getString(6)));return a;}catch(SQLException x){throw new DatabaseOperationException("Join query failed",x);}}
 public List<DepartmentCount> countByDepartment(){String q="SELECT d.department_id,d.department_name,COUNT(e.employee_id) total FROM department d LEFT JOIN employee e ON e.department_id=d.department_id GROUP BY d.department_id,d.department_name ORDER BY d.department_id";List<DepartmentCount>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next())a.add(new DepartmentCount(r.getInt(1),r.getString(2),r.getLong(3)));return a;}catch(SQLException x){throw new DatabaseOperationException("Aggregate query failed",x);}}
 public List<Employee> callEmployeesByDepartment(int dept){List<Employee>a=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();CallableStatement s=c.prepareCall("{call sp_employees_by_department(?)}")){s.setInt(1,dept);try(ResultSet r=s.executeQuery()){while(r.next())a.add(map(r));}return a;}catch(SQLException x){throw new DatabaseOperationException("Stored procedure 1 failed",x);}}
 public int callRaiseDepartmentSalary(int dept,BigDecimal pct){try(Connection c=ConnectionFactory.getConnection();CallableStatement s=c.prepareCall("{call sp_raise_department_salary(?,?,?)}")){s.setInt(1,dept);s.setBigDecimal(2,pct);s.registerOutParameter(3,Types.INTEGER);s.execute();return s.getInt(3);}catch(SQLException x){throw new DatabaseOperationException("Stored procedure 2 failed",x);}}
 public void transferEmployee(int emp,int newDept){String lock="SELECT department_id FROM employee WHERE employee_id=? FOR UPDATE", upd="UPDATE employee SET department_id=? WHERE employee_id=?",log="INSERT INTO employee_transfer_log(employee_id,old_department_id,new_department_id) VALUES(?,?,?)";try(Connection c=ConnectionFactory.getConnection()){c.setAutoCommit(false);try(PreparedStatement a=c.prepareStatement(lock);PreparedStatement b=c.prepareStatement(upd);PreparedStatement d=c.prepareStatement(log)){a.setInt(1,emp);int old;try(ResultSet r=a.executeQuery()){if(!r.next())throw new RecordNotFoundException("Employee "+emp+" not found");old=r.getInt(1);}if(old==newDept)throw new ValidationException("Employee is already in that department");b.setInt(1,newDept);b.setInt(2,emp);b.executeUpdate();d.setInt(1,emp);d.setInt(2,old);d.setInt(3,newDept);d.executeUpdate();c.commit();}catch(Exception x){c.rollback();throw x;}finally{c.setAutoCommit(true);}}catch(SQLException x){throw new DatabaseOperationException("Transfer transaction failed and was rolled back",x);}}
 public int transactionalDepartmentRaise(int dept,BigDecimal pct){String u="UPDATE employee SET salary=salary+(salary*?/100) WHERE department_id=?",a="INSERT INTO salary_audit(department_id,percentage_applied,affected_rows) VALUES(?,?,?)";try(Connection c=ConnectionFactory.getConnection()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement(u);PreparedStatement q=c.prepareStatement(a)){p.setBigDecimal(1,pct);p.setInt(2,dept);int n=p.executeUpdate();if(n==0)throw new RecordNotFoundException("No employees in department "+dept);q.setInt(1,dept);q.setBigDecimal(2,pct);q.setInt(3,n);q.executeUpdate();c.commit();return n;}catch(Exception x){c.rollback();throw x;}finally{c.setAutoCommit(true);}}catch(SQLException x){throw new DatabaseOperationException("Transaction failed and was rolled back",x);}}
 public int[] batchInsert(List<Employee> es){String q="INSERT INTO employee(employee_name,email,salary,department_id,hire_date) VALUES(?,?,?,?,?)";try(Connection c=ConnectionFactory.getConnection();PreparedStatement p=c.prepareStatement(q)){for(Employee e:es){bind(p,e);p.addBatch();}return p.executeBatch();}catch(SQLException x){throw new DatabaseOperationException("Batch insert failed",x);}}
}
